/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ventanas;

import Constructores.ConsEmpleado;
import Constructores.ConsUsuario;
import clases.EmpleadosMet;
import clases.LoginUsuario;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author puppe
 */
public class Usuarios extends javax.swing.JInternalFrame {
ConsUsuario Us = new ConsUsuario();
    LoginUsuario LoginUs = new LoginUsuario();
    EmpleadosMet EmpleadosM = new EmpleadosMet();
    int num;

    // Para la tabla
    DefaultTableModel modelo;
    public Usuarios() {
        initComponents();
        initComponents();
        boxEmpleado.setSelectedIndex(-1);
        LoginUs.ChecarEmpleado(boxEmpleado);
        ListarUsuario();
        verEmpleado();
    }
    public void ListarUsuario() {
        List<ConsUsuario> ListarUsuario = LoginUs.ListarUsuarios();
        modelo = (DefaultTableModel) tbUsuarios.getModel();
        // Creamos el tipo objecto por que es el tipo de dato que utliza la tabla
        Object[] obj = new Object[4];
        for (int i = 0; i < ListarUsuario.size(); i++) {
            obj[0] = ListarUsuario.get(i).getId_usuario();
            obj[1] = ListarUsuario.get(i).getUsuario();
            obj[2] = ListarUsuario.get(i).getContrasena();
            obj[3] = ListarUsuario.get(i).getId_empleado();

            // Lo agregamos a la tabla cada una de las filas
            modelo.addRow(obj);
        }
        tbUsuarios.setModel(modelo);
        tbUsuarios.setRowHeight(40);

    }

    public void LimpiarTabla() {
        for (int i = 0; i < modelo.getRowCount(); i++) {
            modelo.removeRow(i);
            i = i - 1;
        }

    }
    
    public void verEmpleado (){
        DefaultTableModel modelo2;
        // Para que se guarde al empleado ahi
        List<ConsEmpleado> verEmpleado = EmpleadosM.ListarEmpleado();
        //El modelo
        modelo2 = (DefaultTableModel) tbVerEmpleado.getModel();
        //Creamos el objeto donde se guardara 
        Object [] obj = new Object[4];
        for (int i = 0; i < verEmpleado.size(); i++) {
            // se va a obtener del ver empleado los datos de el
            obj[0]=verEmpleado.get(i).getId_empleado();
            obj[1]=verEmpleado.get(i).getNombre();
            obj[2]=verEmpleado.get(i).getApellido();
            obj[3]=verEmpleado.get(i).getPuesto();
            
            // despues lo agg al modelo
            modelo2.addRow(obj);
            
        }
        tbVerEmpleado.setModel(modelo2);
        tbVerEmpleado.setRowHeight(40);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtContrasena = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        boxEmpleado = new javax.swing.JComboBox<>();
        btnModificar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbUsuarios = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbVerEmpleado = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setClosable(true);
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/img/empleados1.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Usuarios", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bookman Old Style", 1, 30), new java.awt.Color(255, 0, 0))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel2.setText("Usuario");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        txtUsuario.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsuario.setBorder(null);
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 130, -1));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel3.setText("Contraseña");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        txtContrasena.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtContrasena.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtContrasena.setBorder(null);
        jPanel1.add(txtContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 130, -1));

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel4.setText("ID Empleado");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        boxEmpleado.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        boxEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxEmpleadoActionPerformed(evt);
            }
        });
        jPanel1.add(boxEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 70, -1));

        btnModificar.setBackground(new java.awt.Color(255, 255, 153));
        btnModificar.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(255, 0, 0));
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 160, -1, 30));

        tbUsuarios.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tbUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Usuario", "Usuario", "Contraseña", "ID Empleado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbUsuarios);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 420, 250));

        btnAgregar.setBackground(new java.awt.Color(255, 255, 153));
        btnAgregar.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 0, 0));
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 60, -1, 30));

        btnEliminar.setBackground(new java.awt.Color(255, 255, 153));
        btnEliminar.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 0, 0));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, -1, 30));

        btnLimpiar.setBackground(new java.awt.Color(255, 255, 153));
        btnLimpiar.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(255, 0, 0));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 110, 30));

        txtId.setEditable(false);
        txtId.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 40, -1));

        tbVerEmpleado.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tbVerEmpleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Empleado", "Nombre", "Apellido", "Puesto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbVerEmpleado.setEnabled(false);
        jScrollPane2.setViewportView(tbVerEmpleado);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 700, 140));

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Empleados");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel5.setText("ID");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, -1, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 771, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boxEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxEmpleadoActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        //Verificar que el id no este vacio
        if (txtId.getText().isEmpty()) {
            System.out.println("Esta vacio");

        } else {
            if (txtUsuario.getText().isEmpty() || txtContrasena.getText().isEmpty() || boxEmpleado.getSelectedIndex() == -1) {
                JOptionPane.showMessageDialog(null,"Los campos estan vacios","Campos Vacios",JOptionPane.QUESTION_MESSAGE);
                System.out.println("Los campos estan vacios");
            } else {
                String contra = String.valueOf(txtContrasena.getPassword());

                int ide = Integer.parseInt(boxEmpleado.getSelectedItem().toString());
                int idu = Integer.parseInt(txtId.getText());
                Us.setUsuario(txtUsuario.getText());
                Us.setContrasena(contra);
                Us.setId_empleado(ide);
                Us.setId_usuario(idu);
                LoginUs.ModificarUsuario(Us);
               limpiar();
                LimpiarTabla();
                ListarUsuario();

            }

        }

    }//GEN-LAST:event_btnModificarActionPerformed

    private void tbUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbUsuariosMouseClicked
        // Para ver si selecciono una fila
        int fila = tbUsuarios.rowAtPoint(evt.getPoint());

        txtId.setText(tbUsuarios.getValueAt(fila, 0).toString());
        txtUsuario.setText(tbUsuarios.getValueAt(fila, 1).toString());
        txtContrasena.setText(tbUsuarios.getValueAt(fila, 2).toString());
        boxEmpleado.setSelectedItem(tbUsuarios.getValueAt(fila, 3));

    }//GEN-LAST:event_tbUsuariosMouseClicked

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // Agregar un usuario
        String contra = String.valueOf(txtContrasena.getPassword());
        int ide = Integer.parseInt(boxEmpleado.getSelectedItem().toString());

        if (txtUsuario.getText().isEmpty() || txtContrasena.getText().isEmpty() || boxEmpleado.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null,"EL campo esta vacio","Campos Vacios",JOptionPane.QUESTION_MESSAGE);
           
        } else {
           

            num=LoginUs.numMaxim();
            System.out.println(num);
            Us.setId_usuario(num);
            Us.setUsuario(txtUsuario.getText());
            Us.setContrasena(contra);
            Us.setId_empleado(ide);
            LoginUs.RegistrarUsuario(Us);
            
            LimpiarTabla();
            ListarUsuario();
              limpiar();
        }

    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (txtId.getText().isEmpty()||txtUsuario.getText().isEmpty() || txtContrasena.getText().isEmpty() || boxEmpleado.getSelectedIndex() == -1) {
           JOptionPane.showMessageDialog(null, "Campos Vacios");
        } else {
            int pregunta = JOptionPane.showConfirmDialog(null, "Estas Seguro de Eliminar");

            if (pregunta == 0) {
                int id = Integer.parseInt(txtId.getText());
                LoginUs.EliminarUsuario(id);
                LimpiarTabla();
                ListarUsuario();
                limpiar();

            }

        }

    }//GEN-LAST:event_btnEliminarActionPerformed
    private void limpiar(){
         txtId.setText("");
        txtUsuario.setText("");
        txtContrasena.setText("");
    }
    
    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
       limpiar();
       tbUsuarios.clearSelection();
    }//GEN-LAST:event_btnLimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxEmpleado;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbUsuarios;
    private javax.swing.JTable tbVerEmpleado;
    private javax.swing.JPasswordField txtContrasena;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
